 
all: clean compile

compile:  
	mkdir build 
	javac -d build -cp lib/asm-3.1.jar:lib/commons-codec-1.3.jar:lib/commons-io-1.4.jar:lib/commons-lang-2.3/commons-lang-2.3-javadoc.jar:lib/commons-lang-2.3/commons-lang-2.3-sources.jar:lib/commons-lang-2.3/commons-lang-2.3.jar:lib/commons-lang-2.3.jar:lib/commons-logging-1.1.jar:lib/fontbox-0.1.0.jar:lib/icu4j-3.4.4.jar:lib/jodconverter.jar:lib/junit-3.8.1.jar:lib/log4j-1.2.14.jar:lib/logging-log4j/log4j-1.2.14.jar:lib/lucene-2.1.0/contrib/analyzers/lucene-analyzers-2.1.0.jar:lib/lucene-2.1.0/contrib/ant/lucene-ant-2.1.0.jar:lib/lucene-2.1.0/contrib/benchmark/lucene-benchmark-2.1.0.jar:lib/lucene-2.1.0/contrib/highlighter/lucene-highlighter-2.1.0.jar:lib/lucene-2.1.0/contrib/lucli/lucene-lucli-2.1.0.jar:lib/lucene-2.1.0/contrib/memory/lucene-memory-2.1.0.jar:lib/lucene-2.1.0/contrib/misc/lucene-misc-2.1.0.jar:lib/lucene-2.1.0/contrib/queries/lucene-queries-2.1.0.jar:lib/lucene-2.1.0/contrib/regex/lucene-regex-2.1.0.jar:lib/lucene-2.1.0/contrib/similarity/lucene-similarity-2.1.0.jar:lib/lucene-2.1.0/contrib/snowball/lucene-snowball-2.1.0.jar:lib/lucene-2.1.0/contrib/spellchecker/lucene-spellchecker-2.1.0.jar:lib/lucene-2.1.0/contrib/surround/lucene-surround-2.1.0.jar:lib/lucene-2.1.0/contrib/swing/lucene-swing-2.1.0.jar:lib/lucene-2.1.0/contrib/wordnet/lucene-wordnet-2.1.0.jar:lib/lucene-2.1.0/contrib/xml-query-parser/lucene-xml-query-parser-2.1.0.jar:lib/lucene-2.1.0/lucene-core-2.1.0.jar:lib/lucene-2.1.0/lucene-demos-2.1.0.jar:lib/lucene-core-2.1.0.jar:lib/lucene-highlighter-2.1.0.jar:lib/nekohtml-0.9.5.jar:lib/ooxml-lib/dom4j-1.6.1.jar:lib/ooxml-lib/jaxen-1.1.jar:lib/ooxml-lib/jsr173_1.0_api.jar:lib/ooxml-lib/ooxml-schemas.jar:lib/ooxml-lib/openxml4j-bin-alpha-080407.jar:lib/ooxml-lib/openxml4j-bin-beta-080728.jar:lib/ooxml-lib/openxml4j-src-alpha-080407.jar:lib/ooxml-lib/xercesImpl-2.8.1.jar:lib/ooxml-lib/xmlbeans-2.3.0.jar:lib/pdfbox-0.7.3.jar:lib/poi-3.5-beta3/poi-3.5-beta3-20080926.jar:lib/poi-3.5-beta3/poi-contrib-3.5-beta3-20080926.jar:lib/poi-3.5-beta3/poi-jdk14-3.5-beta3-20080926.jar:lib/poi-3.5-beta3/poi-ooxml-3.5-beta3-20080926.jar:lib/poi-3.5-beta3/poi-scratchpad-3.5-beta3-20080926.jar:lib/tika-0.2-SNAPSHOT.jar:lib/ws-commons-util-1.0.1.jar:lib/xmlrpc-3.0/lib/commons-logging-1.1.jar:lib/xmlrpc-3.0/lib/ws-commons-util-1.0.1.jar:lib/xmlrpc-3.0/lib/xmlrpc-client-3.0-sources.jar:lib/xmlrpc-3.0/lib/xmlrpc-client-3.0.jar:lib/xmlrpc-3.0/lib/xmlrpc-common-3.0-sources.jar:lib/xmlrpc-3.0/lib/xmlrpc-common-3.0.jar:lib/xmlrpc-3.0/lib/xmlrpc-server-3.0-sources.jar:lib/xmlrpc-3.0/lib/xmlrpc-server-3.0.jar:lib/xmlrpc-common-3.0.jar:lib/xmlrpc-server-3.0.jar \
	 src/com/knowledgetree/lucene/IndexerInterface.java src/com/knowledgetree/lucene/IndexerManager.java src/com/knowledgetree/lucene/QueryHit.java src/com/knowledgetree/metadata/KTMetaData.java src/com/knowledgetree/metadata/KTMetaDataInterface.java src/com/knowledgetree/openoffice/KTConverter.java src/com/knowledgetree/textextraction/KTTextExtractor.java src/com/knowledgetree/textextraction/KTTextExtractorInterface.java src/com/knowledgetree/textextraction/StringHandler.java src/com/knowledgetree/xmlrpc/KTXmlRpcServer.java src/com/knowledgetree/xmlrpc/KTXmlRpcServerInterface.java src/com/knowledgetree/xmlrpc/TokenAuthenticationException.java
	jar cvfm ktlucene.jar MANIFEST.MF -C build/ .

install: 
	cp ktlucene.jar /knowledgetree/ktdms.trunk/bin/luceneserver

clean:
	rm -rf build ktlucene.jar bin
